version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

      # volumes are used to save the database files for persistence.
      # the docker mongo image will remain but the database files(records, tables and info) will be stored in the volume
      # saved on the user computer /data/db foldder
volumes: 
  mongo_data: